server {
	listen 4343;
	root wwwroot/www;

	host 127.0.0.1;
	client_max_body_size 10000000;

	error_page 400 wwwroot/www/error400.html;

	location / {
		#index test.php;
		autoindex on;
		cgi_pass .php /usr/bin/php-cgi;
		allowed_methods GET POST;
	}

	location /upload
	{
		upload_store wwwroot/www/uploads;
		allowed_methods GET POST;
		autoindex on;
	}

	location /test/ {
		return 301 /;
	}
}