server {
	listen 4343;
	client_max_body_size 50;
	root wwwroot/www;
	host 0.0.0.0;

	error_page 400 wwwroot/www/error400.html;

	location / {
		index index.html;
		allowed_methods GET;
	}

	location /test/ {
		return 301 /;
	}
}