server {
	listen 4343;
	root wwwroot/www;
	host 127.0.0.1;
	client_max_body_size 1000;

	error_page 400 wwwroot/www/error400.html;

	location / {
		index test.php;
		cgi_pass .php /usr/bin/php-cgi;
		allowed_methods GET POST;
	}

	location /test/ {
		return 301 /;
	}
}